### ISSUE TITLE
关于项目结构的一些建议

### ISSUE THREAD

**Issue by GoDotDotDot** [frontend9/fe9-market#1]
**纯粹个人建议**

### 【建议】组件应以文件夹为单位

以文件夹为单位可以方便以后对该组件进行拓展，增加只与该组件相关的一些东西，例如增加 `Loadable`， `utils` 等。

示例：
```
components
|----Header
    |----utils
    |----styles
    |----Loadable.js
    |----index.js
```

### 【建议】路由组件应该拆分到 `pages` 文件夹下

路由页面拆分到独立的文件夹下方便维护，一目了然。

示例：
```
pages
|----tool
    |----utils
    |----styles
    |----Loadable.js
    |----index.js
```

### 【建议】可以考虑加一个 `eslintrc` 文件，多人编码尽量定一个编码规范

----

****以上为个人的一些建议，期待能够贡献自己的一份力量。****

**Comment by fkysly** [comment]
对，这三点都需要做，你有兴趣可以提交一个 PR 过来。

**Comment by GoDotDotDot** [comment]
@fkysly 你看看我的[模板](https://github.com/GoDotDotDot/mete-cli/tree/master/templates/react)行不行，有的可能不适合，参考部分结构， 行的话我提交一个 PR 过来

**Comment by fkysly** [comment]
可以的，提个 PR，按照你想的方式来。我只是搭建了一个简单的结构而已。

**Comment by GoDotDotDot** [comment]
@fkysly 好的，今天我提一个 PR。
